/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminRegisterRouteImport } from './routes/admin.register'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/admin/properties',
  path: '/admin/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/properties'
    | '/sitemap.xml'
    | '/testimonials'
    | '/admin/dashboard'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/properties'
    | '/admin/register'
    | '/admin/team'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/properties'
    | '/sitemap.xml'
    | '/testimonials'
    | '/admin/dashboard'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/properties'
    | '/admin/register'
    | '/admin/team'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/properties'
    | '/sitemap.xml'
    | '/testimonials'
    | '/admin/dashboard'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/properties'
    | '/admin/register'
    | '/admin/team'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PropertiesRoute: typeof PropertiesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PropertiesRoute: PropertiesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
